#!/usr/bin/env bash

###
### ## Setup relative sourcing
###
PROJECT_DIR_RELATIVE="$( dirname "$0" )"
PROJECT_DIR_ABSOLUTE="$( cd "$PROJECT_DIR_RELATIVE" && pwd )"
PROJECT_DIR="$PROJECT_DIR_RELATIVE"
source "$PROJECT_DIR/libbootstrap/relative_source.bash"
relative_source libbootstrap.bash

###
### ## Configuration
###

#
# Configure according to ENV
#
_configure "$( cat .env )"

###
### ## Subcommand dispatch
###
#
# If a subcommand is given, evaluate
#
if [ -n "$1" ]
then
  comm=_"$1"; shift;
  eval $comm ${@}
  exit $?
fi

###
### ## Installations
###
#
# If no subcommand is given, install the following packages
# in the following order
#
pkgs=(
  directories
  pyenv
  python
  venv
  venv_activate
  pip
  pipenv
  env_diagnostics
  pipenv_install
)
for pkg in "${pkgs[@]}"
do
  _install_pkg "$pkg" ||
    _err_and_die "$( printf 'Failed while installing unless installed: %s' "$pkg" )"
done &&
  exit 0 ||
  exit 1


sudo mkdir -p /var/postgresql &&
sudo chmod 777 /var/postgresql &&
pg_ctl initdb &&
pg_ctl start &&
createuser airf &&
createdatabase airf &&
true
