#!/usr/bin/env bash

source libbootstrap.bash

###
### ## Argument Check
###
if [[ $(($#)) < 1 ]]
then
  _err_and_die "$( printf 'Syntax:\n  %s ENV\n\n  ENV:\n    One of the environments in %s' "$0" "$_envs_dir" )"
fi

env=$1; shift;
if [ -z "$env" ]
then
  _err_and_die 'ENV (argv[0]) cannot be empty'
fi

_configure "$env"

if [ -n "$1" ]
then
  # Extra arguments given.
  # Dispatch to command:
  comm=_"$1"; shift;
  eval $comm ${@}
  exit $?
fi

#   python \
#   psycopg \
#   airflow
for pkg in \
  directories \
  pyenv \
  venv \
  pip \
  pipenv \

do
  _install_pkg "$pkg" || _err_and_die "$( printf 'Failed while installing unless installed: %s' "$pkg" )"
done &&
exit 0 ||
exit 1

sudo mkdir -p /var/postgresql &&
sudo chmod 777 /var/postgresql &&
pg_ctl initdb &&
pg_ctl start &&
createuser airf &&
createdatabase airf &&
true
