#!/usr/bin/env bash

pg_ctl stop

for f in \
  "$AIRFLOW_HOME" \
  "$AIRFLOW_LOGS" \
  "$AIRFLOW_SCHEDULER_LOGS" \
  "$PGDATA" \
  "$PIPENV_CACHE_DIR" \
  "$PIP_ROOT" \
  "$PYENV_ROOT" \
  "$WORKON_HOME" \
  "$PYTHON_BUILD_CACHE_PATH" \
  .venv/ \
  $HOME/.cache/pip/ \
  $HOME/.cache/pipenv/ \
  $HOME/.cache/pypoetry/ \
  $HOME/.local/app/miniconda/envs/ \
  $HOME/.local/bin/ \
  $HOME/.local/lib/ \
; do
  echo Killing "$f" ...
  rm -rf "$f"
done
