#!/usr/bin/env bash

pg_ctl stop
rm -rfv \
  "$PGDATA" \
  "$PYENV_ROOT" \
  "$AIRFLOW_HOME" \
  "$AIRFLOW_LOGS" \
  "$AIRFLOW_SCHEDULER_LOGS" \
  "$PIPENV_CACHE_DIR" \
  "$WORKON_HOME" \
  .venv/ \
  _pip/ \
  _py36/ \
  $HOME/.cache/pip/ \
  $HOME/.cache/pipenv/ \
  $HOME/.cache/pypoetry/ \
  $HOME/.local/app/miniconda/envs/ \
  $HOME/.local/bin/ \
  $HOME/.local/lib/
